___

<a href='https://www.youtube.com/FallinPython'> <img src="logo_name.jpg" /></a>
___

# NumPy Library

- Different ways to create arrays

## Importing NumPy

In [1]:
import numpy as np

**Note:** To check the content of NumPy library we can use the `dir` function.

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'a

**Note:** To check the doc string we can add a `question mark` after the command

In [3]:
np.sum?

## NumPy Array

Numpy is based on a class called `ndarray`. An object created from this class is referred to `NumPy array` or only `array`.

NumPy comes with a plenty of built-in methods to create `array`. The most used ones are the following:

- `numpy.array()`: Create an array from a Python numerical sequence.

In [4]:
# 1D Array
my_list = [10,20,30]               
my_array = np.array(my_list)

# printing
print(my_list, "⇒", type(my_list))
print(my_array, "  ⇒", type(my_array))

[10, 20, 30] ⇒ <class 'list'>
[10 20 30]   ⇒ <class 'numpy.ndarray'>


In [5]:
# 2D Array
nestedList = [[1, 2, 3],[4, 5, 6],[7,8,9]]
matrix = np.array(nestedList)

# printing
print(matrix)
print()
print(type(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

<class 'numpy.ndarray'>


What if we want to create an array with a large number of elements?

In [6]:
my_list = [x for x in range(21)]
my_array = np.array(my_list)
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


- `numpy.arange()`: Return evenly spaced values within a given interval.

In [10]:
# example 1
#my_array = np.arange(1,21,2)
#print(my_array)

# example 2
start, end, interval = 1, 10, 2
my_array = np.arange(start,end,interval)   # [start, end)
print(my_array)

[1 3 5 7 9]


- `numpy.linspace()`: Return evenly spaced numbers over a specified interval.

In [12]:
start, end, samples = 1, 5, 25
my_array = np.linspace(start,end)  # [start, end]
print(my_array)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


- `numpy.random.randint`: Return random integers from low (inclusive) to high (exclusive).

In [15]:
np.random.randint(0,5,size=(4,3)) # [start, end)

array([[1, 0, 3],
       [4, 2, 3],
       [2, 3, 2],
       [3, 3, 1]])

- `numpy.zeros()`: Return a new array of given shape and type, filled with zeros.

In [18]:
# example 1: 1D array
#my_array = np.zeros(10)
#print(my_array)

# example 2: 2D array
shape = (3,2)
matrix = np.zeros(shape)
print(matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


- `numpy.ones()`: Return a new array of given shape and type, filled with ones.

In [22]:
# example 1: 1D array
#my_array = np.ones(5)
#print(my_array)

# example 2: 2D array
shape = (3,4)
matrix = np.ones(shape)*5
print(matrix)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


- `numpy.identity()`: Return the identity 2D array (ones on the diagonal and zeros elsewhere).

In [24]:
matrix = np.identity(5)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## NumPy Array Methods

In [25]:
my_array = np.arange(1,10)
print(dir(my_array))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [36]:
my_array = np.arange(1,25).reshape(2,3,4)
print(my_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


**Load data from a text file**

In [38]:
fileContent = np.genfromtxt("inputData.txt", delimiter="\t")
print(fileContent)

[[  1.  10.]
 [  2.  20.]
 [  3.  30.]
 [  4.  40.]
 [  5.  50.]
 [  6.  60.]
 [  7.  70.]
 [  8.  80.]
 [  9.  90.]
 [ 10. 100.]]
